In [1]:
import pandas as pd
import numpy as np
from tmdbv3api import TMDb
import json
import requests
tmdb = TMDb()
tmdb.api_key = '94fc0930e034532d61661f5f8efe1bf8'
from tmdbv3api import Movie
tmdb_movie = Movie()

In [2]:
def given_out_put_link(link_of_website):
    Main_df1 = pd.read_html(link_of_website, header=0)[2]
    Main_df2 = pd.read_html(link_of_website, header=0)[3]
    Main_df3 = pd.read_html(link_of_website, header=0)[4]
    Main_df4 = pd.read_html(link_of_website, header=0)[5]
    Main_df = pd.concat([Main_df1, Main_df2, Main_df3, Main_df4], axis=0)
    
    
    def get_genre2(x):
        genres = []
        result = tmdb_movie.search(x)
        movie_id = result[0].id
        response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
        data_json = response.json()
        if data_json['genres']:
            genre_str = " " 
            for i in range(0,len(data_json['genres'])):
                genres.append(data_json['genres'][i]['name'])
                return genre_str.join(genres)
            else:
                np.NaN
        
        
    Main_df['genres'] = Main_df['Title'].map(lambda x: get_genre2(str(x)))
        
    Main_Dataset_of_given_date = Main_df[['Title', 'Cast and crew', 'genres']]
        
    def get_directors(x2):
        if " (director)" in x2:
            return x2.split(" (director)")[0]
        elif " (directors)" in x2:
            return x2.split(" (directors)")[0]
        else:
            return x2.split(" (director/screenplay)")[0]
        
    def get_act1(x3):
        return((x3.split("screenplay); ")[-1]).split(", ")[0])
    
    def get_act2(x4):
        if len((x4.split("screenplay); ")[-1]).split(", ")) < 2:
            return np.NaN
        else:
            return((x4.split("screenplay); ")[-1]).split(", ")[1])
    
    def get_act3(x5):
        if len((x5.split("screenplay); ")[-1]).split(", ")) < 3:
            return np.NaN
        else:
            return((x5.split("screenplay); ")[-1]).split(", ")[2])
            
    Main_Dataset_of_given_date['director_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x2: get_directors(x2))
    Main_Dataset_of_given_date['actor_1_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x3: get_act1(x3))
    Main_Dataset_of_given_date['actor_2_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x4: get_act2(x4))
    Main_Dataset_of_given_date['actor_3_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x5: get_act3(x5))
    
    Main_Dataset_of_given_date = Main_Dataset_of_given_date.rename(columns={'Title':'movie_title'})
    
    New_Data = Main_Dataset_of_given_date.loc[:,['director_name', 'actor_1_name', 'actor_2_name', 'actor_3_name', 'genres', 'movie_title']]
    
    
    New_Data["director_name"].fillna("Unknown", inplace = True)
    New_Data["actor_1_name"].fillna("Unknown", inplace = True)
    New_Data["actor_2_name"].fillna("Unknown", inplace = True)
    New_Data["actor_3_name"].fillna("Unknown", inplace = True)
    
    New_Data['movie_title'] = New_Data['movie_title'].str.lower()
    
    New_Data['Tags'] = New_Data['actor_1_name'] + ' ' + New_Data['actor_2_name'] + ' ' + New_Data['actor_3_name']+ ' ' + New_Data['director_name'] + ' ' + New_Data['genres']
    
    New_Data.drop_duplicates(subset ='movie_title', keep = 'last', inplace=True)
    
    return New_Data

In [3]:
import bs4 as bs
import urllib.request

In [5]:
def given_out_put_link2(link_of_website):
    source = urllib.request.urlopen(link_of_website).read()
    soup = bs.BeautifulSoup(source,'lxml')
    
    tables = soup.find_all('table',class_='wikitable sortable')
    
    Main_df1 = pd.read_html(str(tables[0]))[0]
    Main_df2 = pd.read_html(str(tables[1]))[0]
    Main_df3 = pd.read_html(str(tables[2]))[0]
    Main_df4 =pd.read_html(str(tables[3]).replace("'1\"\'",'"1"'))[0]
    Main_df = pd.concat([Main_df1, Main_df2, Main_df3, Main_df4], axis=0)
    
    
    
    
    def get_genre2(x):
        genres = []
        result = tmdb_movie.search(x)
        if not result:
            return np.NaN
        else:
            movie_id = result[0].id
            response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
            data_json = response.json()
            if data_json['genres']:
                genre_str = " " 
                for i in range(0,len(data_json['genres'])):
                    genres.append(data_json['genres'][i]['name'])
                    return genre_str.join(genres)
                else:
                    return np.NaN
        
        
    Main_df['genres'] = Main_df['Title'].map(lambda x: get_genre2(str(x)))
        
    Main_Dataset_of_given_date = Main_df[['Title', 'Cast and crew', 'genres']]
        
    def get_directors(x2):
        if " (director)" in x2:
            return x2.split(" (director)")[0]
        elif " (directors)" in x2:
            return x2.split(" (directors)")[0]
        else:
            return x2.split(" (director/screenplay)")[0]
        
    def get_act1(x3):
        return((x3.split("screenplay); ")[-1]).split(", ")[0])
    
    def get_act2(x4):
        if len((x4.split("screenplay); ")[-1]).split(", ")) < 2:
            return np.NaN
        else:
            return((x4.split("screenplay); ")[-1]).split(", ")[1])
    
    def get_act3(x5):
        if len((x5.split("screenplay); ")[-1]).split(", ")) < 3:
            return np.NaN
        else:
            return((x5.split("screenplay); ")[-1]).split(", ")[2])
            
    Main_Dataset_of_given_date['director_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x2: get_directors(x2))
    Main_Dataset_of_given_date['actor_1_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x3: get_act1(x3))
    Main_Dataset_of_given_date['actor_2_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x4: get_act2(x4))
    Main_Dataset_of_given_date['actor_3_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x5: get_act3(x5))
    
    Main_Dataset_of_given_date = Main_Dataset_of_given_date.rename(columns={'Title':'movie_title'})
    
    New_Data = Main_Dataset_of_given_date.loc[:,['director_name', 'actor_1_name', 'actor_2_name', 'actor_3_name', 'genres', 'movie_title']]
    
    
    New_Data["director_name"].fillna("Unknown", inplace = True)
    New_Data["actor_1_name"].fillna("Unknown", inplace = True)
    New_Data["actor_2_name"].fillna("Unknown", inplace = True)
    New_Data["actor_3_name"].fillna("Unknown", inplace = True)
    
    New_Data['movie_title'] = New_Data['movie_title'].str.lower()
    
    New_Data['Tags'] = New_Data['actor_1_name'] + ' ' + New_Data['actor_2_name'] + ' ' + New_Data['actor_3_name']+ ' ' + New_Data['director_name'] + ' ' + New_Data['genres']
    
    New_Data.drop_duplicates(subset ='movie_title', keep = 'last', inplace=True)
    
    return New_Data

In [6]:
data_2018 = given_out_put_link('https://en.wikipedia.org/wiki/List_of_American_films_of_2018')

C:\Users\abhin\AppData\Local\Temp\ipykernel_9636\236884433.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Main_Dataset_of_given_date['director_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x2: get_directors(x2))
C:\Users\abhin\AppData\Local\Temp\ipykernel_9636\236884433.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Main_Dataset_of_given_date['actor_1_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x3: get_act1(x3))
C:\Users\abhin\AppData\Local\Temp\ipykernel_9636\236884433.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Main_Dataset_of_given_date['actor_2_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x4: get_act2(x4))
C:\Users\abhin\AppData\Local\Temp\ipykernel_9636\236884433.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Main_Dataset_of_given_date['actor_3_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x5: get_act3(x5))

In [7]:
data_2019 = given_out_put_link('https://en.wikipedia.org/wiki/List_of_American_films_of_2019')

C:\Users\abhin\AppData\Local\Temp\ipykernel_9636\236884433.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Main_Dataset_of_given_date['director_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x2: get_directors(x2))
C:\Users\abhin\AppData\Local\Temp\ipykernel_9636\236884433.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Main_Dataset_of_given_date['actor_1_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x3: get_act1(x3))
C:\Users\abhin\AppData\Local\Temp\ipykernel_9636\236884433.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Main_Dataset_of_given_date['actor_2_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x4: get_act2(x4))

In [8]:
data_2020 = given_out_put_link2('https://en.wikipedia.org/wiki/List_of_American_films_of_2020')

C:\Users\abhin\AppData\Local\Temp\ipykernel_9636\776323968.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Main_Dataset_of_given_date['director_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x2: get_directors(x2))
C:\Users\abhin\AppData\Local\Temp\ipykernel_9636\776323968.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Main_Dataset_of_given_date['actor_1_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x3: get_act1(x3))
C:\Users\abhin\AppData\Local\Temp\ipykernel_9636\776323968.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Main_Dataset_of_given_date['actor_2_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x4: get_act2(x4))
C:\Users\abhin\AppData\Local\Temp\ipykernel_9636\776323968.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Main_Dataset_of_given_date['actor_3_name'] = Main_Dataset_of_given_date['Cast and crew'].map(lambda x5: get_act3(x5))

In [11]:
part1 = pd.concat([data_2018, data_2019, data_2020], axis=0)

In [12]:
part1

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,Tags
0,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Horror,insidious: the last key,Lin Shaye Angus Sampson Leigh Whannell Adam Ro...
1,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Thriller,the strange ones,Alex Pettyfer James Freedson-Jackson Emily Alt...
2,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan,Action,stratton,Dominic Cooper Austin Stowell Gemma Chan Simon...
3,Warwick Thornton,Bryan Brown,Sam Neill,Unknown,Western,sweet country,Bryan Brown Sam Neill Unknown Warwick Thornton...
4,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Action,the commuter,Liam Neeson Vera Farmiga Patrick Wilson Jaume ...
...,...,...,...,...,...,...,...
95,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin,Action,we can be heroes,Priyanka Chopra Jonas Pedro Pascal YaYa Gossel...
96,Paul Greengrass,Tom Hanks,Helena Zengel,Unknown,Drama,news of the world,Tom Hanks Helena Zengel Unknown Paul Greengras...
97,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Drama,one night in miami...,Kingsley Ben-Adir Eli Goree Aldis Hodge Regina...
98,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie,Thriller,promising young woman,Carey Mulligan Bo Burnham Alison Brie Emerald ...
99,Kornél Mundruczó,Vanessa Kirby,Shia LaBeouf,Molly Parker,Drama,pieces of a woman,Vanessa Kirby Shia LaBeouf Molly Parker Kornél...

In [13]:
part1.isnull().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           2
movie_title      0
Tags             2
dtype: int64

In [14]:
old_data = pd.read_csv('new_data2.csv')

old_data

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,Tags
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,Unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker Unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
5359,Jim Strouse,Jessica Williams,Chris O'Dowd,Keith Stanfield,Romance Comedy,the incredible jessica james,Jessica Williams Chris O'Dowd Keith Stanfield ...
5360,Farhad Mann,Adelaide Kane,Benjamin Hollingsworth,Jean Louisa Kelly,Romance,can't buy my love,Adelaide Kane Benjamin Hollingsworth Jean Loui...
5361,Hannaleena Hauru,Inka Haapamäki,Rosa Honkonen,Tiitus Rantala,Romance Comedy,thick lashes of lauri mäntyvaara,Inka Haapamäki Rosa Honkonen Tiitus Rantala Ha...
5362,Jonathan A. Rosenbaum,Lou Diamond Phillips,Wallace Shawn,Gina Holden,Crime Comedy Action Family,cop and a half: new recruit,Lou Diamond Phillips Wallace Shawn Gina Holden...
5363,Ravi Udyawar,Sridevi Kapoor,Sajal Ali,Akshaye Khanna,Crime Drama Thriller,mom,Sridevi Kapoor Sajal Ali Akshaye Khanna Ravi U...

In [15]:
final_data = old_data.append(part1,ignore_index=True)

C:\Users\abhin\AppData\Local\Temp\ipykernel_9636\3457313714.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_data = old_data.append(part1,ignore_index=True)

In [16]:
final_data

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,Tags
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,Unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker Unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
6154,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin,Action,we can be heroes,Priyanka Chopra Jonas Pedro Pascal YaYa Gossel...
6155,Paul Greengrass,Tom Hanks,Helena Zengel,Unknown,Drama,news of the world,Tom Hanks Helena Zengel Unknown Paul Greengras...
6156,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Drama,one night in miami...,Kingsley Ben-Adir Eli Goree Aldis Hodge Regina...
6157,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie,Thriller,promising young woman,Carey Mulligan Bo Burnham Alison Brie Emerald ...
6158,Kornél Mundruczó,Vanessa Kirby,Shia LaBeouf,Molly Parker,Drama,pieces of a woman,Vanessa Kirby Shia LaBeouf Molly Parker Kornél...

In [17]:
final_data.isnull().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           2
movie_title      0
Tags             2
dtype: int64

In [18]:
final_data.to_csv('Finished_data.csv',index=False)